name: Check iStoreOS Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for updates
        id: check
        run: |
          chmod +x ./update_istoreos_image.sh
          ./update_istoreos_image.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request if updated
        if: steps.check.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update iStoreOS image URL to 2025062010"
          title: "Update iStoreOS image URL to 2025062010"
          body: |
            This PR updates the iStoreOS image URL to the latest version.
            
            New URL: https://fw0.koolcenter.com/iStoreOS/x86_64_efi/istoreos-24.10.1-2025062000-x86-64-squashfs-combined-efi.img.gz
          branch: update-istoreos-2025062000
          base: main
